import fs from 'node:fs';
import path from 'node:path';

const root=process.cwd();
const strip=s=>s.replace(/^import .*?;\s*$/gm,'').replace(/\bexport\s+(?=(const|let|var|function|class)\b)/g,'').replace(/^export\s*\{[^}]*\};?\s*$/gm,'');
const addCss=fs.readFileSync(path.join(root,'src','legacy-ui.css'),'utf8');
const v65Css=fs.readFileSync(path.join(root,'src','v65-ui.css'),'utf8');
const v651Css=fs.readFileSync(path.join(root,'src','v651-oncall.css'),'utf8');
const v652Css=fs.readFileSync(path.join(root,'src','v652-oncall.css'),'utf8');
const v653Css=fs.readFileSync(path.join(root,'src','v653-oncall.css'),'utf8');
const v654Css=fs.readFileSync(path.join(root,'src','v654-ui.css'),'utf8');
const v655Css=fs.readFileSync(path.join(root,'src','v655-ui.css'),'utf8');
const v656Css=fs.readFileSync(path.join(root,'src','v656-ui.css'),'utf8');
const v657Css=fs.readFileSync(path.join(root,'src','v657-ui.css'),'utf8');
const v658Css=fs.readFileSync(path.join(root,'src','v658-ui.css'),'utf8');
const v659Css=fs.readFileSync(path.join(root,'src','v659-ui.css'),'utf8');
const v6510Css=fs.readFileSync(path.join(root,'src','v6510-ui.css'),'utf8');
const v6511Css=fs.readFileSync(path.join(root,'src','v6511-ui.css'),'utf8');
const v6512Css=fs.readFileSync(path.join(root,'src','v6512-ui.css'),'utf8');
const v6513Css=fs.readFileSync(path.join(root,'src','v6513-ui.css'),'utf8');
const v6514Css=fs.readFileSync(path.join(root,'src','v6514-ui.css'),'utf8');
const v6515Css=fs.readFileSync(path.join(root,'src','v6515-ui.css'),'utf8');
const modules=['data.js','cache.js','state.js','view-registry.js','performance.js','daily-model.js','risk.js','network-model.js','analytics-model.js','command-palette.js','mobile.js','legacy-overview.js','v64-engine.js','v64-interactive.js','i18n-copy.js','i18n.js','v65-engine.js','oncall.js','v651-engine.js','v652-engine.js','v656-overrides.js','v657-overrides.js','v658-overrides.js','v659-overrides.js','v6510-overrides.js','v6511-overrides.js','v6512-overrides.js','v6513-pwa.js','v6514-mobile.js','v6515-mobile.js'];
const addJs=modules.map(f=>`// ${f}\n${strip(fs.readFileSync(path.join(root,'src',f),'utf8'))}`).join('\n');
const loaderRuntime=`<script id="v65-loader-runtime">(()=>{const root=document.documentElement,o=document.getElementById('bootOverlay');if(!o)return;const b=document.getElementById('boot613Bar'),p=document.getElementById('boot613Pct'),ph=document.getElementById('boot613Phase'),st=document.getElementById('boot613Status'),m=document.getElementById('boot613Meta'),state=document.getElementById('boot613State');let locale='th';try{locale=localStorage.getItem('shift.locale')==='en'?'en':'th'}catch{}root.lang=locale;root.dataset.locale=locale;root.dataset.v65Booting='1';const copy=locale==='en'?[['Initializing Core Systems','Starting…'],['Verifying Shift Matrix','Checking schedule…'],['Linking Command Grid','Connecting widgets…'],['Rendering Interface','Finalizing command center…']]:[['กำลังเริ่มระบบหลัก','กำลังเริ่ม…'],['กำลังตรวจตารางเวร','กำลังตรวจข้อมูล…'],['กำลังเชื่อม Command Grid','กำลังเชื่อมวิดเจ็ต…'],['กำลังเตรียมอินเทอร์เฟซ','กำลังเตรียมหน้าจอ…']];const t0=performance.now(),TARGET=260,HARD=950,COMPLETE_HOLD=80;let domReady=document.readyState!=='loading',done=false,raf=0;if(b){b.style.width='100%';b.style.transition='none';b.style.transformOrigin='left center';b.style.transform='scaleX(0)'}if(!domReady)document.addEventListener('DOMContentLoaded',()=>{domReady=true},{once:true});const release=()=>requestAnimationFrame(()=>requestAnimationFrame(()=>{delete root.dataset.v65Booting;document.dispatchEvent(new CustomEvent('v65:bootrelease'))}));const fade=()=>{o.classList.add('out');release();setTimeout(()=>o.remove(),120)};const finish=()=>{if(done)return;done=true;cancelAnimationFrame(raf);if(b)b.style.transform='scaleX(1)';if(p)p.textContent='100%';if(ph)ph.textContent=locale==='en'?'Interface Ready':'อินเทอร์เฟซพร้อม';if(st)st.textContent=locale==='en'?'Ready':'พร้อมใช้งาน';if(m)m.innerHTML='phase 4 / 4<br>READY';if(state)state.textContent='READY';setTimeout(fade,COMPLETE_HOLD)};const paint=()=>{if(done)return;const elapsed=performance.now()-t0,ratio=Math.min(1,elapsed/TARGET),pct=Math.min(elapsed>=TARGET&&!domReady?99:100,Math.round(ratio*100)),i=pct<25?0:pct<52?1:pct<80?2:3;if(b)b.style.transform='scaleX('+(pct/100)+')';if(p)p.textContent=pct+'%';if(ph)ph.textContent=copy[i][0];if(st)st.textContent=copy[i][1];if(m)m.innerHTML='phase '+(i+1)+' / 4<br>'+(i===3?'FINAL RENDER':'SECURE STARTUP');if(elapsed>=TARGET&&domReady){finish();return}raf=requestAnimationFrame(paint)};raf=requestAnimationFrame(paint);setTimeout(finish,HARD)})();</script>`;
let html=fs.readFileSync(path.join(root,'src','legacy-baseline.html'),'utf8');
html=html.replace("window.scrollTo({top:0,behavior:'smooth'})",'window.scrollTo(0,0)');
html=html.replace('let selectedDay=1,selectedPerson=0','let selectedDay=(()=>{const today=new Date();return today.getFullYear()===2026&&today.getMonth()===9?today.getDate():1})(),selectedPerson=0');
html=html.replace('<html lang="th">','<html lang="th" data-app-version="6.5.15" data-v64-mode="BALANCED" data-v65-mode="BALANCED" data-locale="th" data-v65-booting="1">');
html=html.replace(/<style id="v621-performance-patch">[\s\S]*?<\/style>/i,'');
html=html.replace(/let offTimer=0;const offObserver=new MutationObserver\([\s\S]*?offObserver\.observe\(document\.body,\{subtree:true,childList:true\}\);/,'');
html=html.replace('data-loader-version="6.2.1"','data-loader-version="6.5.15"');
html=html.replace(/<script id="v613-loader-runtime">[\s\S]*?<\/script>/i,loaderRuntime);
html=html.replace('</head>','<link rel="manifest" href="./manifest.webmanifest">\n<meta name="apple-mobile-web-app-capable" content="yes">\n<meta name="apple-mobile-web-app-title" content="Shift">\n<link rel="apple-touch-icon" href="./icons/shift-192.png">\n</head>');
html=html.replace('</head>',`<style id="v64-additive-style">\n${addCss}\n</style>\n<style id="v65-ui-style">\n${v65Css}\n</style>\n<style id="v651-oncall-style">\n${v651Css}\n</style>\n<style id="v652-oncall-style">\n${v652Css}\n</style>\n<style id="v653-oncall-style">\n${v653Css}\n</style>\n<style id="v654-ui-style">\n${v654Css}\n</style>\n<style id="v655-ui-style">\n${v655Css}\n</style>\n<style id="v656-ui-style">\n${v656Css}\n</style>\n<style id="v657-ui-style">\n${v657Css}\n</style>\n<style id="v658-ui-style">\n${v658Css}\n</style>\n<style id="v659-ui-style">\n${v659Css}\n</style>\n<style id="v6510-ui-style">\n${v6510Css}\n</style>\n<style id="v6511-ui-style">\n${v6511Css}\n</style>\n<style id="v6512-ui-style">\n${v6512Css}\n</style>\n<style id="v6513-ui-style">\n${v6513Css}\n</style>\n<style id="v6514-ui-style">\n${v6514Css}\n</style>\n<style id="v6515-ui-style">\n${v6515Css}\n</style>\n</head>`);
html=html.replace('</body>',`<script id="v652-engine">(()=>{\n${addJs}\n})();</script>\n</body>`);
fs.writeFileSync('index.html',html);
const dist=path.join(root,'dist');fs.rmSync(dist,{recursive:true,force:true});fs.mkdirSync(dist,{recursive:true});fs.writeFileSync(path.join(dist,'index.html'),html);
console.log(`built v6.5.15 legacy index.html ${Buffer.byteLength(html)} bytes`);