import {STAFF,dateMeta} from './data.js';
import {createScheduleCache} from './cache.js';
import {createAppState,createViewRegistry} from './core.js';
import {createPerformanceController,scheduleIdle} from './performance.js';
import {startLoader} from './loader.js';
import {dailyModel} from './daily.js';
import {evaluateDayRisk} from './risk.js';
import {networkModel} from './network.js';
import {analyticsModel} from './analytics.js';
import {parseCommandQuery,shouldOpenPalette} from './command-palette.js';
import {renderOverview} from './overview.js';
import {renderPerson} from './person.js';
import {renderMonth} from './month.js';
import {setupMobileSwipe} from './mobile.js';

const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const state=createAppState(),cache=createScheduleCache(STAFF),views=createViewRegistry(),perf=createPerformanceController();
const viewRoot=name=>$(`#${name}View`);
function syncNav(name){state.activeView=name;$$('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===name));$$('.view').forEach(v=>v.classList.toggle('active',v.id===`${name}View`));views.show(name);window.scrollTo({top:0,behavior:'smooth'})}
function selectDay(day){state.setSelectedDay(day);if(views.isMounted('overview'))renderOverviewView();if(views.isMounted('daily'))renderDailyView();if(views.isMounted('analytics'))renderAnalyticsView()}
function selectPerson(i){state.setSelectedPerson(i);syncNav('person')}
function renderOverviewView(){renderOverview(viewRoot('overview'),state,cache,selectDay,selectPerson);renderNetworkPanel()}
function renderDailyView(){const root=viewRoot('daily'),d=state.selectedDay,m=dailyModel(d,cache,STAFF),risks=evaluateDayRisk(d,cache,STAFF),meta=dateMeta(d);const roster=(label,arr)=>`<article class="card roster ${label.toLowerCase()}"><div class="section-head"><div><span class="kicker">${label} SHIFT</span><h2>${label==='D'?'เวรกลางวัน':label==='N'?'เวรกลางคืน':'วันหยุด'}</h2></div><strong>${arr.length}</strong></div>${arr.map(x=>`<button class="person-row" data-person="${x.i}"><span class="avatar">${x.i+1}</span><span><b>${x.name}</b><small>${x.status}</small></span></button>`).join('')||'<p class="empty">ไม่มี</p>'}</article>`;root.innerHTML=`<div class="sticky-daily"><b>${d} ต.ค.</b><span class="d">D ${m.D.length}</span><span class="n">N ${m.N.length}</span><span class="o">OFF ${m.OFF.length}</span><span>${m.coverage}%</span></div><section class="card daily-hero"><div><span class="kicker">DAILY OPERATIONS</span><h1>${meta.thai}</h1><p>${meta.weekday} • Coverage ${m.coverage}%</p></div><div class="daily-controls"><button data-day="${Math.max(1,d-1)}" ${d===1?'disabled':''}>←</button><b>${d}</b><button data-day="${Math.min(31,d+1)}" ${d===31?'disabled':''}>→</button></div></section><section class="rosters">${roster('D',m.D)}${roster('N',m.N)}${roster('OFF',m.OFF)}</section><section class="daily-grid"><article class="card"><div class="section-head"><div><span class="kicker">DAY COMPARISON</span><h2>เทียบวันข้างเคียง</h2></div></div><div class="compare-grid">${['previous','next'].map(k=>{const x=m.comparison[k];return `<div><span>${k==='previous'?'วันก่อน':'วันถัดไป'}</span>${x?`<b>D ${x.D>=0?'+':''}${x.D} • N ${x.N>=0?'+':''}${x.N}</b><small>Coverage ${x.coverage>=0?'+':''}${x.coverage}%</small>`:'<b>N/A</b>'}</div>`}).join('')}</div></article><article class="card"><div class="section-head"><div><span class="kicker">SHIFT TRANSITIONS</span><h2>การเปลี่ยนเวร</h2></div></div><div class="transitions">${m.transitions.slice(0,8).map(x=>`<button data-person="${x.i}"><b>${x.name.replace(/^นาย ?/,'')}</b><span>${x.from} → ${x.to}</span></button>`).join('')||'<p class="empty">ไม่มีการเปลี่ยนสถานะ</p>'}</div></article><article class="card risk-card"><div class="section-head"><div><span class="kicker">STAFFING RISK</span><h2>สัญญาณประจำวัน</h2></div><span class="status-pill ${risks.some(x=>x.level==='critical')?'danger':'ok'}">${risks.length} SIGNALS</span></div><div class="risk-list">${risks.slice(0,10).map(r=>`<div class="risk ${r.level}"><span>${r.code}</span><b>${r.text}</b></div>`).join('')||'<div class="risk ok"><span>ALL CLEAR</span><b>ไม่พบสัญญาณเสี่ยง</b></div>'}</div></article></section>`;root.querySelectorAll('[data-day]').forEach(b=>b.onclick=()=>selectDay(+b.dataset.day));root.querySelectorAll('[data-person]').forEach(b=>b.onclick=()=>selectPerson(+b.dataset.person));}
function renderPersonView(){renderPerson(viewRoot('person'),state,cache,i=>{state.setSelectedPerson(i);renderPersonView()})}
function renderMonthView(){renderMonth(viewRoot('month'),state,d=>{selectDay(d);syncNav('daily')},selectPerson)}
function renderAnalyticsView(){const a=analyticsModel(cache),root=viewRoot('analytics'),d=state.selectedDay;root.innerHTML=`<section class="card"><div class="section-head"><div><span class="kicker">WORKLOAD BALANCE</span><h1>Analytics</h1></div><span class="hint">Team avg ${a.team.avgWork.toFixed(1)} วันทำงาน</span></div><div class="analytics-summary"><div><span>AVG WORK</span><b>${a.team.avgWork.toFixed(1)}</b></div><div><span>AVG N</span><b>${a.team.avgN.toFixed(1)}</b></div><div><span>BUSIEST</span><b>Day ${a.team.busiest.day}</b></div><div><span>LEAST</span><b>Day ${a.team.least.day}</b></div></div><div class="activity-chart">${a.daily.map(x=>`<button data-day="${x.day}" class="${x.day===d?'active':''}" title="Day ${x.day} D${x.D} N${x.N} OFF${x.OFF}"><i style="height:${Math.max(12,x.working*9)}%"></i><span>${x.day}</span></button>`).join('')}</div></section><section class="card table-card"><div class="section-head"><div><span class="kicker">PERSON LOAD</span><h2>สมดุลเวรทั้งทีม</h2></div></div><div class="workload-table"><div class="workload-row head"><span>พนักงาน</span><span>D</span><span>N</span><span>OFF</span><span>WORK</span><span>N%</span><span>STREAK</span><span>Δ AVG</span></div>${a.people.map(p=>`<button class="workload-row" data-person="${p.i}"><span>${p.name.replace(/^นาย ?/,'')}</span><span class="d">${p.D}</span><span class="n">${p.N}</span><span class="o">${p.OFF}</span><span>${p.working}</span><span>${p.nightPct}%</span><span>${p.longestWorkStreak}</span><span>${p.deltaFromAvg>0?'+':''}${p.deltaFromAvg}</span></button>`).join('')}</div></section>`;root.querySelectorAll('[data-day]').forEach(b=>b.onclick=()=>selectDay(+b.dataset.day));root.querySelectorAll('[data-person]').forEach(b=>b.onclick=()=>selectPerson(+b.dataset.person));}
function renderNetworkPanel(){const host=$('#networkPanel');if(!host)return;const limit=innerWidth<700?4:innerWidth<1100?5:6,m=networkModel(state.selectedPerson,cache,limit),center=STAFF[state.selectedPerson];const plotted=m.nodes.map((r,k)=>{const angle=-150+k*(300/Math.max(1,m.nodes.length-1)),rad=angle*Math.PI/180;return {...r,x:50+38*Math.cos(rad),y:52+36*Math.sin(rad)}});host.innerHTML=`<div class="section-head"><div><span class="kicker">TEAM NETWORK 2.0</span><h2>ความสัมพันธ์ของทีม</h2></div><button class="link-btn" id="networkCenter">${center.name.replace(/^นาย ?/,'')}</button></div><div class="network-stage"><svg class="network-edges" viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true">${plotted.map(r=>`<line x1="50" y1="52" x2="${r.x}" y2="${r.y}" style="--strength:${r.strength}"/>`).join('')}</svg><div class="network-core" data-person="${state.selectedPerson}"><span>${state.selectedPerson+1}</span><b>${center.name.replace(/^นาย ?/,'')}</b></div>${plotted.map(r=>`<button class="network-node" style="--x:${r.x}%;--y:${r.y}%;--s:${Math.max(.35,r.strength/100)}" data-person="${r.other}" title="Same ${r.sameShift} • D ${r.sameD} • N ${r.sameN} • Handoff ${r.handoff} • Strength ${r.strength}%"><span>${r.other+1}</span><b>${STAFF[r.other].name.replace(/^นาย ?/,'')}</b><small>${r.strength}%</small></button>`).join('')}</div><div class="network-relations">${m.relations.slice(0,5).map(r=>`<button data-person="${r.other}"><b>${STAFF[r.other].name.replace(/^นาย ?/,'')}</b><span>Same ${r.sameShift} • D ${r.sameD} • N ${r.sameN} • Handoff ${r.handoff}</span><strong>${r.strength}%</strong></button>`).join('')}</div>`;host.querySelectorAll('[data-person]').forEach(b=>b.onclick=()=>{state.setSelectedPerson(+b.dataset.person);renderNetworkPanel()});$('#networkCenter').onclick=()=>syncNav('person')}
views.register('overview',renderOverviewView,renderOverviewView);views.register('daily',renderDailyView,renderDailyView);views.register('person',renderPersonView,renderPersonView);views.register('month',renderMonthView,renderMonthView);views.register('analytics',renderAnalyticsView,renderAnalyticsView);
$$('[data-view]').forEach(b=>b.onclick=()=>syncNav(b.dataset.view));
function setVisual(mode){perf.setVisualMode(mode);$$('[data-quality]').forEach(b=>b.classList.toggle('active',b.dataset.quality===mode))}setVisual('BALANCED');$$('[data-quality]').forEach(b=>b.onclick=()=>setVisual(b.dataset.quality));
const pal=$('#palette'),palInput=$('#paletteInput'),palResults=$('#paletteResults');let palIndex=0,palItems=[];function closePalette(){pal.classList.remove('open')}function drawPalette(){palItems=parseCommandQuery(palInput.value).slice(0,8);palIndex=Math.min(palIndex,Math.max(0,palItems.length-1));palResults.innerHTML=palItems.map((x,i)=>`<button class="${i===palIndex?'active':''}" data-i="${i}"><span>${x.label||x.view||x.code}</span><small>${x.type}</small></button>`).join('')||'<p>ลองพิมพ์วันที่, ชื่อ, night, off, analytics</p>';palResults.querySelectorAll('button').forEach(b=>b.onclick=()=>runPalette(+b.dataset.i))}function runPalette(i){const x=palItems[i];if(!x)return;if(x.type==='day'){selectDay(x.day);syncNav('daily')}else if(x.type==='person')selectPerson(x.i);else if(x.type==='view')syncNav(x.view);else if(x.type==='status')syncNav('daily');closePalette()}function openPalette(){pal.classList.add('open');palInput.value='';palIndex=0;drawPalette();setTimeout(()=>palInput.focus(),10)}
palInput.oninput=drawPalette;palInput.onkeydown=e=>{if(e.key==='ArrowDown'){e.preventDefault();palIndex=Math.min(palItems.length-1,palIndex+1);drawPalette()}if(e.key==='ArrowUp'){e.preventDefault();palIndex=Math.max(0,palIndex-1);drawPalette()}if(e.key==='Enter'){e.preventDefault();runPalette(palIndex)}if(e.key==='Escape')closePalette()};$('#paletteClose').onclick=closePalette;$('#commandBtn').onclick=openPalette;document.addEventListener('keydown',e=>{if(shouldOpenPalette({key:e.key,ctrlKey:e.ctrlKey,metaKey:e.metaKey,targetTag:e.target.tagName,contentEditable:e.target.isContentEditable})){e.preventDefault();openPalette()}else if(e.key==='Escape')closePalette()});
setupMobileSwipe(viewRoot('daily'),delta=>selectDay(state.selectedDay+delta));
views.show('overview');scheduleIdle(()=>{ /* cache already computed; idle slot intentionally left for future derived work */ });startLoader();
window.addEventListener('resize',()=>{if(views.isMounted('overview'))renderNetworkPanel()},{passive:true});
